baseurl = "/"
languageCode = "en-us"
title = "Matthew Baldeosingh's Home"
theme = "hugo-theme-casper"
disqusShortname = "spf13"
# Enable Google Analytics by inserting your tracking code
googleAnalytics = ""
# Define how many posts should appear on a site
paginate = 10
canonifyurls = true

[params]
  description = "Welcome"
  cover = "images/cover.jpg"
  author = "Matthew Baldeosingh"
  authorlocation = "Brooklyn, New York"
  authorwebsite = "baldeosinghm.netlify.com"
  bio= "Junior at Allegheny College"
  logo = "images/logo.png"
  googleAnalyticsUserID = "UA-79101-12"
  # Optional RSS-Link, if not provided it defaults to the standard index.xml
  # RSSLink = "http://feeds.feedburner.com/..."
  githubName = "baldeosinghm"
  # facebookName = ""
  linkedinName = "Matthew Baldeosingh"
  # set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
  hideHUGOSupport = false
  [params.social]
    twitter = "your_twitter"
